### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by mtzern** [nax3t/webdevbootcamp#9]
Hello! 

I'm trying to resolve a problem with "Cannot read property 'substring' of undefined". Unfortunately, I have tried several options, but none of them gives the expected result. I have both deleted the database collection and tried to replace it with the if condition ( index file),

> 
```
<% if(blog.body && blog.body.length > 0) { %> 
   <p><%= blog.body.substring(0, 100)%></p>
<% } > %
```
>

but it does not work and by deleting a post, it actually adds one:
![image](https://user-images.githubusercontent.com/61688268/75667811-e96c9c80-5c80-11ea-90f2-c79640f6700c.png)

What are the possible solutions in this case?

https://goor.me/Ax6az
P.S. added a file of my code at bottom of the page

Thanks in advance,
maox27

[RESTfulRouting.zip](https://github.com/nax3t/webdevbootcamp/files/4274863/RESTfulRouting.zip)

**Comment by mtzern** [comment]
Everyone??

**Comment by LuisGrt** [comment]
Hello @maox27, 

You should use blogs instead of blog, that's the problem you're having with the "Cannot read property 'substring' of undefined" error message.

> <% if(blogs.body && blogs.body.length > 0) { %> 

Anyways it's going to give you an error again on the next line, you can't use substring on an array. You should wrap that logic inside a loop and then use the substring on every element of the array. Remember the substring method is for strings.
